imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  bombardier:
    channel: current
  microbenchmarks:
    source:
      repository: https://github.com/martincostello/adventofcode
      branchOrCommit: main
      project: tests/AdventOfCode.Benchmarks/AdventOfCode.Benchmarks.csproj
    variables:
      filterArg: "*"
      jobArg: short
    arguments: --job {{jobArg}} --filter {{filterArg}} --memory
    channel: current
    options:
      benchmarkDotNet: true
  server:
    source:
      repository: https://github.com/martincostello/adventofcode
      branchOrCommit: main
      project: src/AdventOfCode.Site/AdventOfCode.Site.csproj
    channel: current
    readyStateText: Application started.

scenarios:
  microbenchmarks:
    application:
      framework: net8.0
      job: microbenchmarks
  root:
    application:
      framework: net8.0
      job: server
    load:
      framework: net8.0
      job: bombardier
      variables:
        serverPort: 5000
        path: /

profiles:
  local:
    variables:
      serverAddress: localhost
    jobs:
      application:
        endpoints:
          - http://localhost:5010
      load:
        endpoints:
          - http://localhost:5010
